### ISSUE TITLE
fzf usage from acme/missing `t` cmd file

### ISSUE THREAD

**Issue by Capt0rr** [mkhl/cmd#4]
Hi there.  First, thanks for your blog post on acme, it's probably the best one I've found.

You mention using `t` cmd mapped to `fzf` - I can't figure out how to make it work from within `win` - I get garbage on the screen and it locks up the process.

What's your secret sauce?

(I turned off preview and set colors to bw but I think it's still sending ansi codes for highlighting selected entries which confuses acme)

**Comment by mkhl** [comment]
Ha, I never actually tried running t interactively inside win! 😅
For reference, [my t is here](https://gist.github.com/mkhl/bed3ebd55f45b8f54089a66294c77613#file-t). I usually open the project root directory and run t from inside that window, or from its +Errors window once that's up. T isn't interactive in that case but I can 3 any line from its output.

**Comment by Capt0rr** [comment]
ah, that makes sense now.  `win` is known for being very tricky with interactive tools.

Thanks!
